apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-api-deployment
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: quotes-api
      branch: {{ git_branch }}
  replicas: 1
  template:
    metadata:
      labels:
        app: quotes-api
        branch: {{ git_branch }}
    spec:
      containers:
        - name: quotes-api-container
          image: ruchira088/quotes-api:{{ git_branch }}-{{ git_commit }}
          envFrom:
            - configMapRef:
                name: quotes-api-config-map
            - secretRef:
                name: quotes-api-secrets
          readinessProbe:
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-readiness-probe
          livenessProbe:
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-liveness-probe
          startupProbe:
            periodSeconds: 5
            failureThreshold: 5
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-startup-probe
          ports:
            - name: http4s-port
              containerPort: 8000
