version: "3"

services:

  quotes-api:
    image: quotes-api:latest
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/quotes-api"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "quotes-api"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
