---
- hosts: localhost
  connection: local

  tasks:
    - name: Gather git information
      import_tasks: tasks/git-info.yml

    - name: Build Docker CI image
      shell: |
        docker build \
          -t quotes-api-ci:latest \
          -t quotes-api-ci:{{ git_commit }} \
          -f ../.circleci/Dockerfile .

    - name: Login to Docker Hub
      command: docker login -u {{ docker_username }} -p {{ docker_password }}
      vars:
        docker_username: "{{ lookup('aws_ssm', '/docker-hub/credentials/username', region='ap-southeast-2') }}"
        docker_password: "{{ lookup('aws_ssm', '/docker-hub/credentials/password', region='ap-southeast-2') }}"

    - name: Publish Docker image
      shell: |
        docker tag quotes-api-ci:{{ git_commit }} ruchira088/docker-ci:quotes-api-{{ date }} && \
        docker tag quotes-api-ci:{{ git_commit }} ruchira088/docker-ci:quotes-api && \
        docker push ruchira088/docker-ci:quotes-api-{{ date }} && \
        docker push ruchira088/docker-ci:quotes-api
      vars:
        date: "{{ ansible_date_time.date }}"
